plugins {
	id 'com.android.application'
}

android {
	compileSdkVersion rootProject.ext.compileSdkVersion

	defaultConfig {
		applicationId "com.cube.storm.ui.quiz.example"
		minSdkVersion rootProject.ext.minSdkVersion
		targetSdkVersion rootProject.ext.targetSdkVersion
		multiDexEnabled true
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}

	lintOptions {
		abortOnError false
	}
	namespace 'com.cube.storm.quiz.example'
}

dependencies {
	implementation fileTree(dir: 'libs', include: ['*.jar'])
	implementation project(':library')

	implementation 'androidx.multidex:multidex:2.0.1'
	implementation 'com.3sidedcube.storm:ui:1.8.2'

	compileOnly 'org.projectlombok:lombok:1.18.40'
	annotationProcessor 'org.projectlombok:lombok:1.18.40'
}
